### ISSUE TITLE
Fatal error: Call to undefined method SMW\SQLStore\ChangeOp\TableChangeOp::getFixedPropertyValueBy() in ... ChangeNotification/ChangeNotificationFilter.php on line 148

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticNotifications#17]
### Setup and configuration

- SMW version: 2.4+
- SNO version: 1.0-alpha
- MW version: all

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
Fatal error: Call to undefined method SMW\SQLStore\ChangeOp\TableChangeOp::getFixedPropertyValueBy() in /.../w/extensions/SemanticNotifications/src/ChangeNotification/ChangeNotificationFilter.php on line 148
```

Steps to reproduce the observation (recommendation is to use the [sandbox](http://sandbox.semantic-mediawiki.org)):

http://sandbox.semantic-mediawiki.org/wiki/FileResultDownloadLink

**Comment by mwjames** [comment]
@kghbln Somehow I think the sandbox went back to `Semantic MediaWiki	2.4.1 (320f99b) 17:07, 8 September 2016` according to [0].

This is way `SMW\SQLStore\ChangeOp\TableChangeOp::getFixedPropertyValueBy` cannot be found.

[0] http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version.

**Comment by kghbln** [comment]
Indeed this [happened yesterday](https://wikiapiary.com/w/index.php?title=Semantic_MediaWiki_-_Sandbox%2FExtensions&type=revision&diff=3116802&oldid=3111915) which surprises me since the [setup remains unchanged](http://sandbox.semantic-mediawiki.org/wiki/SMW_Sandbox:Setup_information#composer.local.json). The only thing I did yesterday was to update PHP from 5.6.24 to 5.6.26 All the rest remained unchanged . So either Maps is causing this or Scribunto. Will have a look tomorrow.

**Comment by mwjames** [comment]
Since we expect this extension to work with 2.4, I added https://github.com/SemanticMediaWiki/SemanticNotifications/commit/e2f648cde1220d088b35db79d30737a68bcbadcc.

**Comment by kghbln** [comment]
> Since we expect this extension to work with 2.4, I added e2f648c.

Thanks for fixing along the way. While testing https://github.com/JeroenDeDauw/Maps/issues/263 I found out that master of Maps is causing the revert back to SMW 2.4.1 Pinging @JeroenDeDauw for future fluff in this respect
